### ISSUE TITLE
Kilometraje total 0xB7 y 0xB8

### ISSUE THREAD

**Issue by vicmanmo** [CamiAlfa/M365-BLE-PROTOCOL#3]
//kilometraje patinete metros, los 4 bits están concatenados 0xb8 es el mas significativo

¿Como se calcula el total de kilómetros con los dos valores?

Agradecer el gran trabajo que has hecho, es impresionante.

**Comment by CamiAlfa** [comment]
En hex  x01 x02 x03 x04, al concatenarlo y te quedas con 0x01020304
