### ISSUE TITLE
Problema recibiendo respuestas cuando la luz frontal está encendida

### ISSUE THREAD

**Issue by fmenendez** [CamiAlfa/M365-BLE-PROTOCOL#6]
Hola Camilo,

Te escribo porque estoy sufriendo un problema muy extraño y me gustaría preguntarte si tú también lo has sufrido para ver si me podrías ayudar. Mi problema es que tengo una aplicación que se comunica con un M365 utilizando el puerto serie, después de mucho pelear he podido hacer que funcione, quiero decir, he podido enviar mensajes al M365 y recibir respuestas. Pero me ha surgido un problema cuando he encendido la luz delantera, porque de repente dejo de recibir respuestas del M365, aunque recibo mensajes, ninguno de ellos es un mensaje de respuesta a las peticiones que le envío, ¿sabe cuál podría ser el problema? Si es así, ¿sabes cómo se puede arreglar?

Muchas gracias de antemano por su respuesta.

Atentamente.

**Comment by fmenendez** [comment]
Hola,

Solo para dar un poco más de información sobre el problema, proporciono el script de Python que estoy usando para probar este problema, tal vez hay algo incorrecto en el comando o en otra parte:

import serial
import time

while (True):
ser = serial.Serial();
ser.baudrate = 115200;
#ser.port = '/dev/ttyUSB0';
ser.port = 'COM5';
ser.parity=serial.PARITY_NONE;
ser.stopbits=serial.STOPBITS_ONE;
ser.bytesize=serial.EIGHTBITS;
ser.timeout=0.05;
ser.open();
ser.write("55aa0322011012b7ff".decode('hex'));
ser.flush();
s = ser.read(1024);
ser.close();
hex = s.encode('hex');
if (hex.find("55aa1425") != -1):
print (hex);
time.sleep(0.01);

Si imprimo todos los mensajes recibidos de M365, en lugar de solo los de respuesta como lo hago en el script, estos son los mensajes que recibo cuando enciendo la luz:

55aa07206500042629000020ff55aa0920640006262900007200abfe55aa062164000007640009ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa07206500042629000020ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa0920640006262900007200abfe55aa062164000007640009ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa07206500042629000020ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa0920640006262900007200abfe55aa062164000008640008ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
0160004403042629000020ff55aa07206500042629000020ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa0920640006262900007200abfe55aa062164000008640008ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa0920640006262900007200abfe55aa062164000008640008ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa0920640006262900007200abfe55aa062164000008640008ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa07206500042629000020ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa0920640006262900007200abfe55aa062164000008640008ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------
55aa07206500042629000020ff55aa07206500042629000020ff
-------------------------------------------------- ----------------------------

Como se puede ver no recibo ningún mensaje como:

55aa1453f70306038826c98028d8ff474a3138493741323031301501781ecdfb

lo que significa una respuesta a mi solicitud ...

Un saludo.

**Comment by CamiAlfa** [comment]
Podría ser que hayas fundido el fusible f2 de la controladora, puedes reemplazarlo o puentearlo. Al encender la luz se cae el voltaje (a causa del fusible roto) y ocurren cosas de ese estilo. En casos extremos se empiezan a perder los mensajes de control del acelerador y el freno y el patinete empieza a dar tirones
